name: Extraer y procesar datos

on:
  schedule:
    - cron: '0 0 * * *'  # Esto ejecuta el workflow todos los días a las 00:00 UTC
  push:
    branches:
      - main  # O cualquier rama en la que quieras activar el flujo de trabajo
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  extraer_datos:
    runs-on: ubuntu-latest  # Usa la imagen más reciente de Ubuntu para ejecutar el workflow

    steps:
    - name: Hacer checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Puedes usar la versión de Python que prefieras

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib requests

    - name: Descargar datos
      run: |
        python tu_script_de_descarga.py  # Aquí llamas a tu script para descargar los datos

    - name: Generar reporte
      run: |
        python tu_script_de_reportes.py  # Aquí llamas a tu script que genera los reportes

    - name: Subir datos y reportes al repositorio
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Actualización diaria de datos y reportes'
